FROM jupyter/scipy-notebook:latest

USER root

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

USER jovyan
